create table havells(
ITEM_ID INT,
ITEM_NAME VARCHAR(20),
ITEM_PRICE VARCHAR(20)
)

create table  DISTRIBUTAR(
ITEM_ID INT,
ITEM_NAME VARCHAR(20),
ITEM_PRICE VARCHAR(20)
)
create table  SHOP(
ITEM_ID INT,
ITEM_NAME VARCHAR(20),
ITEM_PRICE VARCHAR(20)
)

INSERT INTO SHOP VALUES (101,'AC','2000')
INSERT INTO SHOP VALUES (102,'IRON','3000')
INSERT INTO SHOP VALUES (103,'PRESS','4000')
INSERT INTO SHOP VALUES (104,'LAPTOP','45000')
INSERT INTO SHOP VALUES (105,'COMPUTER','55000')


SELECT * FROM havells
SELECT * FROM DISTRIBUTAR
SELECT * FROM SHOP
MERGE INTO DISTRIBUTAR DI
USING HAVELLS HA
ON(DI.ITEM_ID= HA.ITEM_ID)
WHEN NOT MATCHED BY TARGET 
THEN 
INSERT (ITEM_ID,ITEM_NAME,ITEM_PRICE)
VALUES (HA.ITEM_ID,HA.ITEM_NAME,HA.ITEM_PRICE)
WHEN MATCHED
THEN 
UPDATE  SET DI.ITEM_PRICE=HA.ITEM_PRICE;

MERGE INTO SHOP SH
USING DISTRIBUTAR DI
ON(SH.ITEM_ID= DI.ITEM_ID)
WHEN NOT MATCHED BY TARGET 
THEN 
INSERT (ITEM_ID,ITEM_NAME,ITEM_PRICE)
VALUES (DI.ITEM_ID,DI.ITEM_NAME,DI.ITEM_PRICE)
WHEN MATCHED
THEN 
UPDATE  SET SH.ITEM_PRICE=DI.ITEM_PRICE;


